services:
  db-tienda:
    image: postgres:16
    environment:
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda
      POSTGRES_DB: tienda
    ports:
      - "5433:5432"
    volumes:
      - tienda-data:/var/lib/postgresql/data

volumes:
  tienda-data:
